// Generated by CoffeeScript 1.7.1
(function() {
  var GSBasic;

  GSBasic = (function() {
    function GSBasic() {}

    GSBasic.prototype["if"] = function(a, b, c) {
      debug("if(%s,%s,%s)", a, b, c);
      if (a) {
        return b;
      } else {
        return c;
      }
    };

    GSBasic.prototype["<"] = function(l, r) {
      return l < r;
    };

    GSBasic.prototype[">"] = function(l, r) {
      return l > r;
    };

    GSBasic.prototype["+"] = function(l, r) {
      return l + r;
    };

    GSBasic.prototype["-"] = function(l, r) {
      return l - r;
    };

    GSBasic.prototype["\\"] = function(l, r) {
      return Number(l) / Number(r);
    };

    GSBasic.prototype.mod = function(l, r) {
      return l % r;
    };

    GSBasic.prototype["/"] = function(l, r) {
      return l / r;
    };

    GSBasic.prototype["*"] = function(l, r) {
      return l * r;
    };

    GSBasic.prototype["=="] = function(l, r) {
      return l === r;
    };

    GSBasic.prototype.schmu = function(args) {
      return console.log("schmu: " + args);
    };

    GSBasic.prototype.print = function(args) {
      window.green(args);
      return "green(" + args + ")";
    };

    GSBasic.prototype.def = function(k, v) {
      console.log("DEF %s %s", k, v);
      return window.gosub.scope[k] = v;
    };

    GSBasic.prototype["let"] = function(args) {
      return args;
    };

    GSBasic.prototype._get = function(k) {
      var v;
      v = window.gosub.scope[k];
      console.log("GET %s => %s", k, v);
      if (v) {
        return window.gosub.scope[k];
      } else {
        return console.log("UNDEFINED: %s", k);
      }
    };

    return GSBasic;

  })();

  window.gosub || (window.gosub = {});

  window.gosub.scope = new GSBasic();

}).call(this);
